### ISSUE TITLE
Milestone 02

### ISSUE THREAD

**Issue by hadleyd2** [STAT547-UBC-2019-20/group_09#24]
Hello @kristinawright,

Could you let me know when you are planning to work on milestone 02? I would like to have some time to review your work and make any suggestions/changes before the grace period is up, and I won't have a lot of time to do it Monday. If you do not have time today, I am going to start on the remaining tasks later tonight.

Also let me know if you need help or are running into any issues with the additions from my last pull request.

Thanks!
-Dan

**Comment by kristinawright** [comment]
Hey @hadleyd2 ,

In the pull request I have:
-milestone 1: changed the font sizes on our plots and removed the redundancy in the correlogram 
-milestone2: added the exploratory data analysis script for all 3 plots, added images saved from this script, added an rmd of the start of the report (some of it had code in the comments about the plots, which I removed for now and we can work on later since there is no longer any code in it for the plotting. )

As for the exploratory data analysis plots, I saw you filtered the data based on price in the processing of data, so I made the density plot, violin plot and correlogram with this filtered/clean data only.

**Comment by kristinawright** [comment]
please check over new pull request with EDA edits with new clean data (non filtered) @hadleyd2

**Comment by hadleyd2** [comment]
Thanks @kristinawright! Your changes look great!
