### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by kristinawright** [STAT547-UBC-2019-20/group_09#29]
@hadleyd2  are you ready to tag a release and hand it in on canvas?

**Comment by hadleyd2** [comment]
@kristinawright I would like to make some minor updates first. 

Unfortunately, I am not able to do it at this moment. I may need an hour or so. I should have a pull request ready for your review by 9:30PM or will update this issue again with a new timeline.

**Comment by hadleyd2** [comment]
Just added a pull request [here](https://github.com/STAT547-UBC-2019-20/group_09/pull/30). All I ended up doing was updating the README file. The inclusion list (for required packages) and usage list should now be formatted properly. I updated the milestone01 html link and added the milestone02 link. I removed `ggplot2` from the list of required packages since it is automatically installed with `tidyverse`. I added `scales` as an additional package. Finally, I updated the usage for the exploratory data analysis script to point to the `scripts` subdirectory when calling the script (to keep consistent with Firas' example for milestone02) and added changed the output directory to `images/milestone02` since the images are saved in that sub-directory.  

Let me know if there are any further issues with the README file. Otherwise, I am good.

Thanks!

**Comment by kristinawright** [comment]
Looks good!  nice job.  I can submit it on canvas at 3ish today unless you do it before me.

**Comment by hadleyd2** [comment]
@kristinawright 

I made some final changes since the images were not rendering online or locally. I changed the image directories to be dynamic to the `docs` folder where the html file is located, changed the title of our Milestone02 document from Milestone01, changed the due date to March 7.

I tagged a [release](https://github.com/STAT547-UBC-2019-20/group_09/releases/tag/v2.0), submitted our release to Canvas, and had contributions as 50/50. If you disagree, please let me know.

Thanks!
-Dan
